//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService2Soap")]
    public interface WebService2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getItem(string query, string ddlChoose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItem", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getItemAsync(string query, string ddlChoose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getItems(string query, string ddlChoose);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getItemsAsync(string query, string ddlChoose);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : WebShop.ServiceReference2.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<WebShop.ServiceReference2.WebService2Soap>, WebShop.ServiceReference2.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getItem(string query, string ddlChoose) {
            return base.Channel.getItem(query, ddlChoose);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getItemAsync(string query, string ddlChoose) {
            return base.Channel.getItemAsync(query, ddlChoose);
        }
        
        public System.Data.DataTable getItems(string query, string ddlChoose) {
            return base.Channel.getItems(query, ddlChoose);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getItemsAsync(string query, string ddlChoose) {
            return base.Channel.getItemsAsync(query, ddlChoose);
        }
    }
}
