//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginCheck", ReplyAction="*")]
        WebShop.ServiceReference1.LoginCheckResponse LoginCheck(WebShop.ServiceReference1.LoginCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<WebShop.ServiceReference1.LoginCheckResponse> LoginCheckAsync(WebShop.ServiceReference1.LoginCheckRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginCheck", Namespace="http://tempuri.org/", Order=0)]
        public WebShop.ServiceReference1.LoginCheckRequestBody Body;
        
        public LoginCheckRequest() {
        }
        
        public LoginCheckRequest(WebShop.ServiceReference1.LoginCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public LoginCheckRequestBody() {
        }
        
        public LoginCheckRequestBody(string userName, string pass) {
            this.userName = userName;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginCheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebShop.ServiceReference1.LoginCheckResponseBody Body;
        
        public LoginCheckResponse() {
        }
        
        public LoginCheckResponse(WebShop.ServiceReference1.LoginCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginCheckResult;
        
        public LoginCheckResponseBody() {
        }
        
        public LoginCheckResponseBody(bool LoginCheckResult) {
            this.LoginCheckResult = LoginCheckResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebShop.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebShop.ServiceReference1.WebService1Soap>, WebShop.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebShop.ServiceReference1.LoginCheckResponse WebShop.ServiceReference1.WebService1Soap.LoginCheck(WebShop.ServiceReference1.LoginCheckRequest request) {
            return base.Channel.LoginCheck(request);
        }
        
        public bool LoginCheck(string userName, string pass) {
            WebShop.ServiceReference1.LoginCheckRequest inValue = new WebShop.ServiceReference1.LoginCheckRequest();
            inValue.Body = new WebShop.ServiceReference1.LoginCheckRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.pass = pass;
            WebShop.ServiceReference1.LoginCheckResponse retVal = ((WebShop.ServiceReference1.WebService1Soap)(this)).LoginCheck(inValue);
            return retVal.Body.LoginCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebShop.ServiceReference1.LoginCheckResponse> WebShop.ServiceReference1.WebService1Soap.LoginCheckAsync(WebShop.ServiceReference1.LoginCheckRequest request) {
            return base.Channel.LoginCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.ServiceReference1.LoginCheckResponse> LoginCheckAsync(string userName, string pass) {
            WebShop.ServiceReference1.LoginCheckRequest inValue = new WebShop.ServiceReference1.LoginCheckRequest();
            inValue.Body = new WebShop.ServiceReference1.LoginCheckRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.pass = pass;
            return ((WebShop.ServiceReference1.WebService1Soap)(this)).LoginCheckAsync(inValue);
        }
    }
}
